version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: mocchi-affiliate
      POSTGRES_PASSWORD: mocchi-affiliate
      POSTGRES_DB: mocchi-affiliate
