db:
  url: ${DATABASE_URL:postgresql://localhost:5434/mocchi-affiliate}
  username: ${JDBC_DATABASE_USERNAME:mocchi-affiliate}
  password: ${JDBC_DATABASE_PASSWORD:mocchi-affiliate}

stripe:
  apiKey: ${STRIPE_API_KEY}
  clientId: ${STRIPE_API_CLIENT_ID}

auth0:
  domain: ${AUTH_DOMAIN}
  clientId: ${AUTH_CLIENT_ID}
  clientSecret: ${AUTH_CLIENT_SECRET}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://${AUTH_DOMAIN}/.well-known/jwks.json
          issuer-uri: https://${AUTH_DOMAIN}/
